;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="RF.Components.InteractionTrigger",DevComment="")
+GameplayTagList=(Tag="RF.Components.InteractionWidget",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.Cards",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.CurrentPlayerIndex",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.NPCDiscardNum",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.NPCHand",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.NPCPass",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.Player",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PlayerDiscardNum",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PlayerHand",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PlayerPass",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PoolMoney",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PotMoney",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.RoundNumber",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.Score",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.ScoreMultiplier",DevComment="")

