;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="RF.PokerState.HumanDiscardNum",NewTagName="RF.PokerState.HumanPlayerDiscardNum")
+GameplayTagList=(Tag="RF.Components.InteractionTrigger",DevComment="")
+GameplayTagList=(Tag="RF.Components.InteractionWidget",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.Cards",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.CurrentPlayerIndex",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.CurrentTurn",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.DiscardedHand",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.DiscardNum",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.DiscardStatus",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.DoubleDownStatus",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.FoldStatus",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.GameEndStatus",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.HumanMoney",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.HumanPlayer",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.HumanPlayerHand",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.NPCHand",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.NPCMoney",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PassStatus",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PoolMoney",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.PotMoney",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.RankedHands",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.RoundEnd",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.RoundNum",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.RoundRestart",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.Score",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.ScoreMultiplier",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.Widget",DevComment="")
+GameplayTagList=(Tag="RF.PokerState.WinningPlayer",DevComment="")

